### ISSUE TITLE
Add Good Programs

### ISSUE THREAD

**Issue by Harsh-jot** [Harsh-jot/HacktoberFest-2023#19]
Create and Add your Projects or relevant Programs in any of your Basic Programming Languages

**Comment by coder-pink** [comment]
@Harsh-jot Please assign it to me

**Comment by Harsh-jot** [comment]
> @Harsh-jot Please assign it to me

You can add some programs.

**Comment by vedali29** [comment]
can you please assign it me. i do have some good codes. please assign it to me.

**Comment by Adidem23** [comment]
I want to add AI Algorithms in the programs Directory 
like 
- A* Star 
- Greedy Algorithm
- BFS , DFS 
- Constraint Satisfication Problems
- TicTacToe
